version: "3.8"

services:
  mongo:
    image: mongo
    ports: 
      - 27018:27017
  
  express:
    image: node:current-alpine
    working_dir: /app
    volumes: 
      - ./backend:/app
    #build:
      #context: ./backend
    ports:
      - 5000:5000
    depends_on: 
      - mongo
    command: sh -c "npm install && npm start"
      #localhost:container 
  vue:
    image: node:current-alpine
    environment: 
      # If you have with hot realoading need add this#
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    volumes: 
      - ./frontend:/app
    ports:
      - 8080:8080
    depends_on: 
      - express
    command: sh -c "npm install && npm run serve"