version: "3.8"

services:
  mongo:
    image: mongo

  express:
    image: node:current-alpine
    working_dir: /app
    environment: 
      MONGO_URL: "mongodb://mongo/todos"
      PORT: 5000
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    command: sh -c "npm install && npm start"

  vue:
    image: node:current-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 8080:8080
    stdin_open: true
    command: sh -c "npm install && npm run serve"
    depends_on:
      - express
